### ISSUE TITLE
Unable to load pyfdax with python3

### ISSUE THREAD

**Issue by Godtec** [chipmuenk/pyFDA#136]
mikek@mikek-MSI:~/Documents/SDR_Radio/pyFDA$ pyfdax
Traceback (most recent call last):
  File "/usr/local/bin/pyfdax", line 11, in <module>
    load_entry_point('pyfda==0.1.5', 'console_scripts', 'pyfdax')()
  File "/home/mikek/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 479, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/mikek/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2703, in load_entry_point
    return ep.load()
  File "/home/mikek/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2321, in load
    return self.resolve()
  File "/home/mikek/.local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2327, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.6/dist-packages/pyfda-0.1.5-py3.6.egg/pyfda/pyfdax.py", line 35, in <module>
    from pyfda.pyfda_lib import to_html
  File "/usr/local/lib/python3.6/dist-packages/pyfda-0.1.5-py3.6.egg/pyfda/pyfda_lib.py", line 22, in <module>
    import scipy.signal as sig
  File "/usr/lib/python3/dist-packages/scipy/signal/__init__.py", line 274, in <module>
    from . import sigtools
ImportError: cannot import name 'sigtools'

----------------------------------------------

I do agree that I have issues with my dual Python 2.7 & 3.6.
Do you have any idea where I can start to solve this?

sigtools has been installed both with python 2.7 and 3.6..

Also, is there a way to run from python directly.
(Sorry if I these questions are dumb, still learning Python)

Thanks.
MikeK

**Comment by chipmuenk** [comment]
Hm, that looks like an installation issue to me. How did you install Python / pyfda? I haven't tried starting pyfda from another python script (if that's what you want) but this should be possible via the main file pyfdax.py

I'm afraid those are no dumb questions, I've had enough problems myself running python scripts and getting all the imports right.

Unfortunately, I'll be quite busy till the end of the year and can't put much effort in supporting pyfda at the moment.

**Comment by animeshsrivastava24** [comment]
I found the following discussions. Please refer to these. @Godtec 
[[SciPy-User] Can not import sigtools (latest svn, python 3.1)](https://mail.python.org/pipermail/scipy-user/2010-November/027544.html)

**Comment by chipmuenk** [comment]
I'll leave the issue open for others who might have the same problem. Concerning GSoC: Could you please send me a PM if you are still interested?

**Comment by chipmuenk** [comment]
Seems unrelated to pyfda - closing.
