### ISSUE TITLE
Tests test_float2frmt_csd and test_float2frmt_hex for pyfda_fix_lib fail

### ISSUE THREAD

**Issue by chipmuenk** [chipmuenk/pyFDA#138]
test_float2frmt_csd
=====================================
FAIL: Conversion from float and dec to CSD format
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/chipmuenk/pyFDA/pyfda/tests/test_pyfda_fix_lib.py", line 323, in test_float2frmt_csd
    self.assertEqual(yq_list, yq_list_goal)
AssertionError: Lists differ: ['-', '-', '0', '0', '0', '0', '0', '0', '+'] != ['-.000000', '-.00000+', '-.0+0+0+', '0.0000[52 chars]00-']
First differing element 0:
'-'
'-.000000'
- ['-', '-', '0', '0', '0', '0', '0', '0', '+']
+ ['-.000000',
+  '-.00000+',
+  '-.0+0+0+',
+  '0.00000-',
+  '0',
+  '0.00000+',
+  '+.0-0-0-',
+  '+.0-0-0-',
+  '+.00000-']

test_float2frmt_hex
===============================================================
FAIL: Conversion from float to hex format
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/chipmuenk/pyFDA/pyfda/tests/test_pyfda_fix_lib.py", line 274, in test_float2frmt_hex
    self.assertEqual(yq_list, yq_list_goal)
AssertionError: Lists differ: ['7F', '7F', '00', '00', '00', '00', '00', '00', '01'] != ['1.00', '1.04', '1.84', '1.FC', '0.00', '0.04', '0.7C', '0.80', '0.FC']
First differing element 0:
'7F'
'1.00'
- ['7F', '7F', '00', '00', '00', '00', '00', '00', '01']
+ ['1.00', '1.04', '1.84', '1.FC', '0.00', '0.04', '0.7C', '0.80', '0.FC']

**Comment by chipmuenk** [comment]
Fixed by commit  951af43.
