### ISSUE TITLE
Matplotlib 3.1.0: KeyError 'back' in NavigationToolbar

### ISSUE THREAD

**Issue by chipmuenk** [chipmuenk/pyfda#153]
Running pyfda with matplotlib 3.1.0 yields the following error (which doesn't happen under matplotlib 3.0.3):

Python: 3.7.3
pyQt: 5.9.2
Anaconda distribution, Ubuntu 18.04 64 bit

---------------------------------------------------------------
(base) cmuenker@cmuenker-TUXEDO:~/Daten/design/python/git/pyfda/pyfda/plot_widgets$ python -m pyfda.plot_widgets.plot_phi
Traceback (most recent call last):
  File "/home/cmuenker/anaconda3/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/cmuenker/anaconda3/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/cmuenker/Daten/design/python/git/pyfda/pyfda/plot_widgets/plot_phi.py", line 233, in <module>
    main()
  File "/home/cmuenker/Daten/design/python/git/pyfda/pyfda/plot_widgets/plot_phi.py", line 227, in main
    mainw = Plot_Phi(None)
  File "/home/cmuenker/Daten/design/python/git/pyfda/pyfda/plot_widgets/plot_phi.py", line 37, in __init__
    self._construct_UI()
  File "/home/cmuenker/Daten/design/python/git/pyfda/pyfda/plot_widgets/plot_phi.py", line 106, in _construct_UI
    self.mplwidget = MplWidget(self)
  File "/home/cmuenker/Daten/design/python/git/pyfda/pyfda/plot_widgets/mpl_widget.py", line 90, in __init__
    self.mplToolbar = MplToolbar(self.pltCanv, self) # inherits all methods
  File "/home/cmuenker/Daten/design/python/git/pyfda/pyfda/plot_widgets/mpl_widget.py", line 233, in __init__
    NavigationToolbar.__init__(self, *args, **kwargs)
  File "/home/cmuenker/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 685, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "/home/cmuenker/anaconda3/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2638, in __init__
    self.set_history_buttons()
  File "/home/cmuenker/anaconda3/lib/python3.7/site-packages/matplotlib/backends/backend_qt5.py", line 854, in set_history_buttons
    self._actions['back'].setEnabled(can_backward)
KeyError: 'back'

**Comment by chipmuenk** [comment]
Appearently, this is fixed in Matplotlib 3.1.1 (https://github.com/matplotlib/matplotlib/pull/14319).
