### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by TaoTaoUncle** [chipmuenk/pyfda#158]
i just run 'pyfdx' in my mac bash.
Error happened:

YDE:pyfda liutao$ pyfdax
Created logging directory /var/folders/fk/t0w1yvc130j2gp3tmg28l99r0000gn/T/.pyfda
[   INFO] [pyfda.pyfda_rc:191] Using 'DejaVu Sans' font.
[  DEBUG] [pyfda.tree_builder:135] Config file: /Users/liutao/.pyfda/pyfda.conf

[   INFO] [pyfda.tree_builder:259] Parsing config file
	"/Users/liutao/.pyfda/pyfda.conf"
		with sections:
	['Dirs', 'Input Widgets', 'User Input Widgets', 'Plot Widgets', 'User Plot Widgets', 'Filter Designs', 'User Filter Designs', 'Fixpoint Widgets', 'User Fixpoint Widgets']
[WARNING] [pyfda.tree_builder:398] No section [Common] in config file "/Users/liutao/.pyfda/pyfda.conf".
Traceback (most recent call last):
  File "/usr/local/bin/pyfdax", line 11, in <module>
    load_entry_point('pyfda', 'console_scripts', 'pyfdax')()
  File "/Users/liutao/Documents/git/pyfda/pyfda/pyfdax.py", line 290, in main
    mainw = pyFDA()
  File "/Users/liutao/Documents/git/pyfda/pyfda/pyfdax.py", line 133, in __init__
    _ = Tree_Builder() # TODO_ couldn't this be a function?
  File "/Users/liutao/Documents/git/pyfda/pyfda/tree_builder.py", line 137, in __init__
    self.init_filters()
  File "/Users/liutao/Documents/git/pyfda/pyfda/tree_builder.py", line 173, in init_filters
    self.parse_conf_file()
  File "/Users/liutao/Documents/git/pyfda/pyfda/tree_builder.py", line 271, in parse_conf_file
    .format(dirs.USER_CONF_DIR_FILE, CONF_VERSION, int(self.commons['version'][0])))
KeyError: 'version'

**Comment by TaoTaoUncle** [comment]
Ok, i fix it finally.
just delete the file——/Users/liutao/.pyfda/
