### ISSUE TITLE
Pyfda crash with matplotlib 3.2

### ISSUE THREAD

**Issue by Magine96** [chipmuenk/pyfda#171]
With matplotlib 3.2, pyfda crashes with the attached traceback. The root cause is that the names for reversed colormaps like `hot_r` have been eliminated from `cm.datad`. New colormaps like `viridis` are also missing (https://github.com/matplotlib/matplotlib/issues/5202/). 

The crash is being fixed by commits 38f7698 and 2bc1949, new colormaps are still missing.

Traceback (most recent call last):
  File "C:\Users\marti\AppData\Local\Programs\Python\Python37-32\Scripts\pyfdax-script.py", line 11, in <module>
    load_entry_point('pyfda==0.3.0', 'console_scripts', 'pyfdax')()
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\pyfda\pyfdax.py", line 290, in main
    mainw = pyFDA()
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\pyfda\pyfdax.py", line 134, in __init__
    self._construct_UI()
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\pyfda\pyfdax.py", line 147, in _construct_UI
    pltTabWidgets = plot_tab_widgets.PlotTabWidgets(self) # plot widgets
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\pyfda\plot_widgets\plot_tab_widgets.py", line 34, in __init__
    self._construct_UI()
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\pyfda\plot_widgets\plot_tab_widgets.py", line 72, in _construct_UI
    inst = wdg_class(self)
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\pyfda\plot_widgets\plot_3d.py", line 74, in __init__
    self._construct_UI()
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\pyfda\plot_widgets\plot_3d.py", line 232, in _construct_UI
    self._init_grid() # initialize grid and do initial plot
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\pyfda\plot_widgets\plot_3d.py", line 328, in _init_grid
    self.draw() # initial plot
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\pyfda\plot_widgets\plot_3d.py", line 424, in draw
    self.draw_3d()
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\pyfda\plot_widgets\plot_3d.py", line 444, in draw_3d
    cmap = cm.get_cmap(str(self.cmbColormap.currentText()))
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\matplotlib\cm.py", line 134, in get_cmap
    cbook._check_in_list(sorted(cmap_d), name=name)
  File "c:\users\marti\appdata\local\programs\python\python37-32\lib\site-packages\matplotlib\cbook\__init__.py", line 2145, in _check_in_list
    .format(v, k, ', '.join(map(repr, values))))
ValueError: '' is not a valid value for name; supported values are 'Accent', 'Accent_r', 'Blues', 'Blues_r', 'BrBG', 'BrBG_r', 'BuGn', 'BuGn_r', 'BuPu', 'BuPu_r', 'CMRmap', 'CMRmap_r', 'Dark2', 'Dark2_r', 'GnBu', 'GnBu_r', 'Greens', 'Greens_r', 'Greys', 'Greys_r', 'OrRd', 'OrRd_r', 'Oranges', 'Oranges_r', 'PRGn', 'PRGn_r', 'Paired', 'Paired_r', 'Pastel1', 'Pastel1_r', 'Pastel2', 'Pastel2_r', 'PiYG', 'PiYG_r', 'PuBu', 'PuBuGn', 'PuBuGn_r', 'PuBu_r', 'PuOr', 'PuOr_r', 'PuRd', 'PuRd_r', 'Purples', 'Purples_r', 'RdBu', 'RdBu_r', 'RdGy', 'RdGy_r', 'RdPu', 'RdPu_r', 'RdYlBu', 'RdYlBu_r', 'RdYlGn', 'RdYlGn_r', 'Reds', 'Reds_r', 'Set1', 'Set1_r', 'Set2', 'Set2_r', 'Set3', 'Set3_r', 'Spectral', 'Spectral_r', 'Wistia', 'Wistia_r', 'YlGn', 'YlGnBu', 'YlGnBu_r', 'YlGn_r', 'YlOrBr', 'YlOrBr_r', 'YlOrRd', 'YlOrRd_r', 'afmhot', 'afmhot_r', 'autumn', 'autumn_r', 'binary', 'binary_r', 'bone', 'bone_r', 'brg', 'brg_r', 'bwr', 'bwr_r', 'cividis', 'cividis_r', 'cool', 'cool_r', 'coolwarm', 'coolwarm_r', 'copper', 'copper_r', 'cubehelix', 'cubehelix_r', 'flag', 'flag_r', 'gist_earth', 'gist_earth_r', 'gist_gray', 'gist_gray_r', 'gist_heat', 'gist_heat_r', 'gist_ncar', 'gist_ncar_r', 'gist_rainbow', 'gist_rainbow_r', 'gist_stern', 'gist_stern_r', 'gist_yarg', 'gist_yarg_r', 'gnuplot', 'gnuplot2', 'gnuplot2_r', 'gnuplot_r', 'gray', 'gray_r', 'hot', 'hot_r', 'hsv', 'hsv_r', 'inferno', 'inferno_r', 'jet', 'jet_r', 'magma', 'magma_r', 'nipy_spectral', 'nipy_spectral_r', 'ocean', 'ocean_r', 'pink', 'pink_r', 'plasma', 'plasma_r', 'prism', 'prism_r', 'rainbow', 'rainbow_r', 'seismic', 'seismic_r', 'spring', 'spring_r', 'summer', 'summer_r', 'tab10', 'tab10_r', 'tab20', 'tab20_r', 'tab20b', 'tab20b_r', 'tab20c', 'tab20c_r', 'terrain', 'terrain_r', 'twilight', 'twilight_r', 'twilight_shifted', 'twilight_shifted_r', 'viridis', 'viridis_r', 'winter', 'winter_r'

C:\Users\marti>pip list qt
Package            Version
------------------ -------
attrs              19.3.0
backcall           0.1.0
bleach             3.1.3
colorama           0.4.3
cycler             0.10.0
decorator          4.4.2
defusedxml         0.6.0
docutils           0.16
entrypoints        0.3
importlib-metadata 1.5.0
ipykernel          5.1.4
ipython            7.13.0
ipython-genutils   0.2.0
jedi               0.16.0
Jinja2             2.11.1
json5              0.9.3
jsonschema         3.2.0
jupyter-client     6.1.0
jupyter-core       4.6.3
jupyterlab-server  1.0.7
kiwisolver         1.1.0
MarkupSafe         1.1.1
matplotlib         3.2.1
migen              0.9.2
mistune            0.8.4
nbconvert          5.6.1
nbformat           5.0.4
nose               1.3.7
notebook           6.0.3
numpy              1.18.2
pandocfilters      1.4.2
parso              0.6.2
pickleshare        0.7.5
pip                19.2.3
prometheus-client  0.7.1
prompt-toolkit     3.0.4
pyfda              0.3.0
Pygments           2.6.1
pyparsing          2.4.6
PyQt5              5.14.1
PyQt5-sip          12.7.1
pyrsistent         0.15.7
python-dateutil    2.8.1
pywin32            227
pywinpty           0.5.7
pyzmq              19.0.0
scipy              1.4.1
Send2Trash         1.5.0
setuptools         41.2.0
six                1.14.0
terminado          0.8.3
testpath           0.4.4
tornado            6.0.4
traitlets          4.3.3
wcwidth            0.1.8
webencodings       0.5.1
zipp               3.1.0
WARNING: You are using pip version 19.2.3, however version 20.0.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\marti>python
Python 3.7.7 ...

**Comment by chipmuenk** [comment]
Fixed in v0.3.0.
