### ISSUE TITLE
Filter type "Delay" can crash pyfda

### ISSUE THREAD

**Issue by chipmuenk** [chipmuenk/pyfda#184]
When changing e.g. from an IIR bandpass filter to an FIR filter of type "Delay", strange things can happen

`
[input_specs.py:353] can only concatenate str (not "dict") to str
`
or
```
[   INFO] [pyfda.input_widgets.input_specs:302] Start filter design using method
        'Equiripple.LPman'
[   INFO] [pyfda.input_widgets.input_specs:336] Designed filter with order = 10
[   INFO] [pyfda.pyfdax:291] Logging to C:\Users\Chris\AppData\Local\Temp\.pyfda\pyfda.log
[   INFO] [pyfda.pyfdax:292] Using 'pyfda' style sheet.
[   INFO] [pyfda.pyfdax:300] Starting pyfda with screen resolution: 2560 x 1440
[   INFO] [pyfda.input_widgets.input_specs:302] Start filter design using method
        'Equiripple.HPman'
[   INFO] [pyfda.input_widgets.input_specs:336] Designed filter with order = 10
[   INFO] [pyfda.input_widgets.input_specs:302] Start filter design using method
        'Equiripple.HPmin'
[   INFO] [pyfda.input_widgets.input_specs:336] Designed filter with order = 24
[   INFO] [pyfda.input_widgets.input_specs:302] Start filter design using method
        'Ellip.BPmin'
[   INFO] [pyfda.input_widgets.input_specs:336] Designed filter with order = 4
Traceback (most recent call last):
  File "d:\daten\design\python\git\pyfda\pyfda\input_widgets\select_filter.py", line 187, in <lambda>
    lambda: self._set_filter_type(enb_signal=True))  #'IIR'
  File "d:\daten\design\python\git\pyfda\pyfda\input_widgets\select_filter.py", line 284, in _set_filter_type
    self._set_design_method(enb_signal)
  File "d:\daten\design\python\git\pyfda\pyfda\input_widgets\select_filter.py", line 321, in _set_design_method
    fb.fil[0]['fo'] = list(fb.fil_tree[self.rt][self.ft][fc].keys())[0]
IndexError: list index out of range
```
Sometimes even the filter list is changed and the Delay type appears in the combo box for IIR filter design classes.

**Comment by chipmuenk** [comment]
This was due to a faulty definition in the UI section of the delay filter.
